<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1d1f7ff45c0aa2529dd792b2e402c673
{
    public static $prefixesPsr0 = array (
        'x' => 
        array (
            'xrstf\\Composer52' => 
            array (
                0 => __DIR__ . '/..' . '/xrstf/composer-php52/lib',
            ),
        ),
    );

    public static $classMap = array (
        'IWPML_ST_Page_Translations_Persist' => __DIR__ . '/../..' . '/classes/filters/db-cache/persist/interface-iwpml-st-page-translations-persist.php',
        'IWPML_St_Upgrade_Command' => __DIR__ . '/../..' . '/classes/upgrade/interface-iwpml_st_upgrade_command.php',
        'WPML_Admin_Notifier' => __DIR__ . '/../..' . '/classes/class-wpml-admin-notifier.php',
        'WPML_Auto_Loader' => __DIR__ . '/..' . '/wpml/commons/src/wpml-auto-loader.php',
        'WPML_Autoregister_Context_Exclude' => __DIR__ . '/../..' . '/classes/filters/autoregister/class-wpml-autoregister-context-exclude.php',
        'WPML_Autoregister_Save_Strings' => __DIR__ . '/../..' . '/classes/filters/autoregister/class-wpml-autoregister-save-strings.php',
        'WPML_Change_String_Domain_Language_Dialog' => __DIR__ . '/../..' . '/classes/string-translation-ui/class-wpml-change-string-domain-language-dialog.php',
        'WPML_Change_String_Language_Dialog' => __DIR__ . '/../..' . '/classes/string-translation-ui/class-wpml-change-string-language-dialog.php',
        'WPML_Custom_Post_Slug_UI' => __DIR__ . '/../..' . '/classes/slug-translation/class-wpml-custom-post-slug-ui.php',
        'WPML_Dependencies' => __DIR__ . '/..' . '/wpml/commons/src/dependencies/class-wpml-dependencies.php',
        'WPML_Displayed_String_Filter' => __DIR__ . '/../..' . '/classes/filters/class-wpml-displayed-string-filter.php',
        'WPML_Language_Of_Domain' => __DIR__ . '/../..' . '/classes/class-wpml-language-of-domain.php',
        'WPML_Register_String_Filter' => __DIR__ . '/../..' . '/classes/filters/class-wpml-register-string-filter.php',
        'WPML_Rewrite_Rule_Filter' => __DIR__ . '/../..' . '/classes/slug-translation/class-wpml-rewrite-rule-filter.php',
        'WPML_ST_Admin_Blog_Option' => __DIR__ . '/../..' . '/classes/admin-texts/class-wpml-st-admin-blog-option.php',
        'WPML_ST_Admin_Option_Translation' => __DIR__ . '/../..' . '/classes/admin-texts/class-wpml-st-admin-option-translation.php',
        'WPML_ST_Admin_String' => __DIR__ . '/../..' . '/classes/class-wpml-st-admin-string.php',
        'WPML_ST_Blog_Name_And_Description_Hooks' => __DIR__ . '/../..' . '/classes/filters/class-wpml-st-blog-name-and-description-hooks.php',
        'WPML_ST_DB_Cache' => __DIR__ . '/../..' . '/classes/filters/db-cache/class-wpml-st-db-cache.php',
        'WPML_ST_DB_Cache_Factory' => __DIR__ . '/../..' . '/classes/filters/db-cache/class-wpml-st-db-cache-factory.php',
        'WPML_ST_DB_Chunk_Retrieve' => __DIR__ . '/../..' . '/classes/filters/db-cache/class-wpml-st-db-chunk-retrieve.php',
        'WPML_ST_DB_Translation_Retrieve' => __DIR__ . '/../..' . '/classes/filters/db-cache/class-wpml-st-db-translation-retrieve.php',
        'WPML_ST_Domain_Fallback' => __DIR__ . '/../..' . '/classes/filters/db-cache/class-wpml-st-domain-fallback.php',
        'WPML_ST_ICL_String_Translations' => __DIR__ . '/../..' . '/classes/records/class-wpml-st-icl-string-translations.php',
        'WPML_ST_ICL_Strings' => __DIR__ . '/../..' . '/classes/records/class-wpml-st-icl-strings.php',
        'WPML_ST_Label_Translation' => __DIR__ . '/../..' . '/classes/filters/class-wpml-st-label-translation.php',
        'WPML_ST_Page_Translation' => __DIR__ . '/../..' . '/classes/filters/db-cache/class-wpml-st-page-translation.php',
        'WPML_ST_Page_Translations' => __DIR__ . '/../..' . '/classes/filters/db-cache/class-wpml-st-page-translations.php',
        'WPML_ST_Page_Translations_Persist' => __DIR__ . '/../..' . '/classes/filters/db-cache/persist/class-wpml-st-page-translations-persist.php',
        'WPML_ST_Page_URL_Preprocessor' => __DIR__ . '/../..' . '/classes/filters/db-cache/class-wpml-st-page-url-preprocessor.php',
        'WPML_ST_Records' => __DIR__ . '/../..' . '/classes/records/class-wpml-st-records.php',
        'WPML_ST_Reset' => __DIR__ . '/../..' . '/classes/class-wpml-st-reset.php',
        'WPML_ST_Settings' => __DIR__ . '/../..' . '/classes/class-wpml-st-settings.php',
        'WPML_ST_String' => __DIR__ . '/../..' . '/classes/class-wpml-st-string.php',
        'WPML_ST_String_Factory' => __DIR__ . '/../..' . '/classes/class-wpml-st-string-factory.php',
        'WPML_ST_String_Statuses' => __DIR__ . '/../..' . '/classes/class-wpml-st-string-statuses.php',
        'WPML_ST_Strings' => __DIR__ . '/../..' . '/classes/class-wpml-st-strings.php',
        'WPML_ST_TM_Jobs' => __DIR__ . '/../..' . '/classes/wpml-tm/class-wpml-st-tm-jobs.php',
        'WPML_ST_Themes_And_Plugins_Settings' => __DIR__ . '/../..' . '/classes/strings-scanning/class-wpml-themes-and-plugins-settings.php',
        'WPML_ST_Themes_And_Plugins_Updates' => __DIR__ . '/../..' . '/classes/strings-scanning/class-wpml-themes-and-plugins-updates.php',
        'WPML_ST_Upgrade' => __DIR__ . '/../..' . '/classes/upgrade/class-wpml-st-upgrade.php',
        'WPML_ST_Upgrade_Command_Factory' => __DIR__ . '/../..' . '/classes/upgrade/class-wpml-st-upgrade-command-factory.php',
        'WPML_ST_Upgrade_Command_Not_Found_Exception' => __DIR__ . '/../..' . '/classes/upgrade/class-wpml-st-upgrade-command-not-found-exception.php',
        'WPML_ST_Upgrade_Db_Cache_Command' => __DIR__ . '/../..' . '/classes/upgrade/class-wpml-st-upgrade-db-cache-command.php',
        'WPML_ST_Upgrade_Display_Strings_Scan_Notices' => __DIR__ . '/../..' . '/classes/upgrade/class-wpml-st-upgrade-display-strings-scan-notices.php',
        'WPML_ST_Upgrade_Migrate_Originals' => __DIR__ . '/../..' . '/classes/upgrade/class-wpml-st-upgrade-migrate-originals.php',
        'WPML_ST_User_Fields' => __DIR__ . '/../..' . '/classes/class-wpml-st-user-fields.php',
        'WPML_ST_Verify_Dependencies' => __DIR__ . '/../..' . '/classes/class-wpml-st-verify-dependencies.php',
        'WPML_ST_WP_Loaded_Action' => __DIR__ . '/../..' . '/classes/actions/class-wpml-st-wp-loaded-action.php',
        'WPML_ST_WP_Wrapper' => __DIR__ . '/../..' . '/classes/filters/db-cache/class-wpml-st-wp-wrapper.php',
        'WPML_String_Translation_Table' => __DIR__ . '/../..' . '/classes/string-translation-ui/class-wpml-string-translation-table.php',
        'WPML_TM_Filters' => __DIR__ . '/../..' . '/classes/filters/class-wpml-tm-filters.php',
        'WPML_TM_Widget_Filter' => __DIR__ . '/../..' . '/classes/filters/class-wpml-tm-widget-filter.php',
        'WPML_Twig_WP_Plugin_Extension' => __DIR__ . '/..' . '/wpml/commons/src/twig-extensions/wpml-twig-wp-plugin-extension.php',
        'WPML_post_slug_translation_settings' => __DIR__ . '/../..' . '/classes/slug-translation/class-wpml-post-slug-translation-settings.php',
        'xrstf\\Composer52\\AutoloadGenerator' => __DIR__ . '/..' . '/xrstf/composer-php52/lib/xrstf/Composer52/AutoloadGenerator.php',
        'xrstf\\Composer52\\Generator' => __DIR__ . '/..' . '/xrstf/composer-php52/lib/xrstf/Composer52/Generator.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit1d1f7ff45c0aa2529dd792b2e402c673::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit1d1f7ff45c0aa2529dd792b2e402c673::$classMap;

        }, null, ClassLoader::class);
    }
}
